# Test Configuration for Bank Nifty Strategy
broker:
  name: "mock"
  api_key: "test_api_key"
  api_secret: "test_api_secret"
  access_token: "test_access_token"
  user_id: "test_user"

strategy:
  capital: 500000
  max_risk_per_trade: 0.05
  profit_target: 0.10
  strike_percentages:
    - 0.5
    - 1.0
    - 1.5
    - 2.0
  execution_time: "15:00"
  timezone: "Asia/Kolkata"

market_data:
  primary_source: "mock"
  backup_source: "mock"
  
risk:
  max_positions: 10
  margin_buffer: 1.2
  max_drawdown: 0.15
  
logging:
  level: "INFO"
  file: "logs/test_trading.log"
  max_size_mb: 10
  backup_count: 5

backtest:
  start_date: "2024-01-01"
  end_date: "2024-12-31"
  initial_capital: 500000
  commission: 20

notifications:
  enabled: false
